config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  get "/dashboard", to: "users#dashboard"
  resources :users, only: [:update]

  get '/djs/:genres', to: 'dj_profiles#genre', as: 'genre'

  resources :dj_profiles

  resources :bookings do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dj_profile
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :set_length, presence: true
end

app/models/dj_profile.rb
class DjProfile < ApplicationRecord
  belongs_to :user

  has_many :bookings
  has_many :reviews, through: :bookings

  validates :genres, presence: true

  validates :stage_name, presence: true
  validates :bio, presence: true

  GENRES = ['Disco', 'Deep House', 'House', 'Techno', 'Minimal', 'Electro', 'All DJs']

  def self.genres
    GENRES
  end

  def avg_rating
    self.reviews.map { |r| r.fyre_stars }.reduce(:+) / self.reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :fyre_stars, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dj_profiles
  has_many :bookings
  has_many :dj_profile_bookings, through: :dj_profiles, class_name: "Booking", source: :bookings

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    # @booking.dj_profile =
    if @booking.save!
      redirect_to dj_profile_path(@booking.dj_profile), notice: "Your booking request has been sent!"
    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to dashboard_path(current_user), notice: 'Your booking request has been updated succesfully'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path(@booking.user)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:name, :date, :location, :set_length, :dj_profile_id, :validated)
  end
end

app/controllers/dj_profiles_controller.rb
class DjProfilesController < ApplicationController
  before_action :set_dj_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :genre]

  # @positions = # draw table dj positions here
  # [[205, 210, 150, 1], [150, 340, 165, 850], [300, 330, 125, 860], [350, 185, 165, 65], [560, 225, 170, 65], [495, 530, 100, 905], [530, 340, 230, 35], [450, 340, 140, 860], [353, 440, 140, 10], [270, 430, 140, 900], [140, 490, 165, 850], [280, 565, 165, 0], [400, 560, 185, 0]] #check if 0 as z-index causes a problem

  def index
    @dj_profiles = DjProfile.all
  end

  # we can see all dj profiles
  def show
    # @dj_profiles = DjProfile.all
    @bookings = Booking.all
    @booking = Booking.new
  end

  # we can create a new dj profile
  def new
    @dj_profile = DjProfile.new
  end

  def genre
    @genre = params[:genres]
    @djs = DjProfile.select { |dj| dj.genres.include?(@genre) }
  end

  # as a user owning a dj profile i can edit it
  def edit
  end

  # POST the new profile
  def create
    @dj_profile = DjProfile.new(dj_params)
    @dj_profile.user = current_user
    @dj_profile.genres = [params[:dj_profile][:genres]]
    if @dj_profile.save
      redirect_to dj_profile_path(@dj_profile), notice: 'Your Dj profile has been created succesfully!'
    else
      render :new
    end
  end

  # PATCH/PUT as a user owning a dj profile i can update it
  def update
    if @dj_profile.update(dj_params)
      redirect_to dj_profile_path(@dj_profile), notice: 'Your Dj profile has been updated succesfully'
    else
      render :edit
    end
  end

  # As a user i can delete my dj profile
  def destroy
    @dj_profile.destroy
    redirect_to dj_profile_path(@dj_profile)
  end

  private

  def set_dj_profile
    @dj_profile = DjProfile.find(params[:id])
  end

  def dj_params
    params.require(:dj_profile).permit(:genre, :stage_name, :bio)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if params[:query].nil? == false
      @query = params[:query]
      @query == "All DJs" ? @dj_profiles = DjProfile.all.sample(33) : @dj_profiles = DjProfile.where("'#{params[:query]}' = ANY (genres)").sample(21)
    else
      @dj_profiles = DjProfile.all.sample(33)
    end
    # if params search, get specific profiles with where genres inlude celui cherche
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # @review = Review.find(params[:review_id])
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = booking
    @review.save!
    redirect_to dashboard_path
  end

  private

  def review_params
    params.require(:review).permit(:comment, :fyre_stars)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    @bookings_user = current_user.bookings
    if  current_user.dj_profiles.any?
      @bookings_dj = current_user.dj_profiles.first.bookings
    end
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="dj-card">
  <%= simple_form_for(@booking) do |b| %>
    <%= b.error_notification %>
    <%= b.error_notification message: b.object.errors[:base].to_sentence if b.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= b.input :name %>
      <%= b.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%#= b.input :date %>
      <%= b.input :location %>
      <%= b.input :set_length %>
      <%= b.input :dj_profile_id, as: :hidden, input_html: {value: @dj_profile.id } %>
    </div>

    <div class="form-actions">
      <%= b.button :submit, class:"btn-ghost-orange ml-4 mt-4" %>
    </div>
  <% end %>
</div>

app/views/dj_profiles/genre.html.erb
<div class="container">
  <h1>Our DJs that play <%= @genre %></h1>

  <%= link_to 'All our DJs', dj_profiles_path, class: "btn btn-secondary" %>


  <div class="index-container">
    <% @djs.each do |dj_profile| %>
      <%= link_to dj_profile_path(dj_profile) do %>
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path dj_profile.user.photo %>')"></div>
          <span><%= dj_profile.stage_name %></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dj_profiles/index.html.erb
<div class="container">
  <h1>Find your perfect DJ in our roster !</h1>
  <div class="dropdown">
    <h5>What kind of music do you like ?</h5>
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Chose your genre
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%  DjProfile.genres.each do |genre| %>
      <%= link_to genre, genre_path(genre), class:"dropdown-item"  %>
      <% end %>
    </div>
  </div>

  <div class="index-container">
    <% @dj_profiles.each do |dj_profile| %>
      <%= link_to dj_profile_path(dj_profile) do %>
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path dj_profile.user.photo %>')"></div>
          <span><%= dj_profile.stage_name %></span>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/dj_profiles/show.html.erb
  <div class="container">

    <div class="djdetails">

      <!-- Left card -->
      <div class="dj-card" id="bio">
        <h3>BIO</h3>
        <p><%= @dj_profile.bio %></p>

        <p class="mt-4" style="font-weight:500">Listen to <%= @dj_profile.stage_name%> on Soundcloud</p>
        <%= link_to (@dj_profile.social_media), target: :_blank do %>
          <i class="fab fa-soundcloud"></i></p>
          <% end %>
      </div>

      <!-- Central card -->
      <div class="dj-card">

        <% if @dj_profile.user.photo.file.nil? %>
          <%= image_tag "https://www.residentadvisor.net/images/profiles/breitlitz.jpg", alt: @dj_profile.stage_name, class:"avatar-large" %>
        <% else %>
          <%= cl_image_tag @dj_profile.user.photo, alt: @dj_profile.stage_name, class:"avatar-large" %>
        <% end %>

        <h1 class="dj-name"><%= @dj_profile.stage_name %></h1>

        <%#= link_to "BOOK THE ARTIST", "#collapseExample", class:"btn-ghost-orange mt-3", id:"booking-btn"  %>
        <a href="#collapseExample" data-scroll class="btn-ghost-orange mt-3" id="booking-btn">BOOK THE ARTIST</a>

        <p>Genres</p>
          <div class="genres">
          <% @dj_profile.genres.each do |genre| %>
          <div  class="genre-name">  <%= link_to genre, genre_path(genre), class:"genre-name"  %></div>
            <% end %>
          </div>
        </p>

             <div class="mt-3">
              <% if @dj_profile.reviews.blank?  %>
              <p>This DJ has not been rated yet.</p>
              <% else %>
                <p>Average Fyre rating</p>
                <% @dj_profile.avg_rating.round.times do %>
                  <i class="fas fa-fire" style="color:#BC5100; font-size:30px;"></i>
                <% end %>
                  <% (5-@dj_profile.avg_rating.round).times do %>
                  <i class="fas fa-fire" style="color:#E5E5E5; font-size:30px;"></i>
                <% end %>
                <p class="reviews-count">out of <%= @dj_profile.reviews.count %> review(s)</p>
              <% end %>

            </div>



      </div>

      <!-- Right card -->
      <!-- We need to show all past bookings before validation -->
      <div class="dj-card" id="past-events">
        <!-- <h3 class="mb-0"><%#= @dj_profile.stage_name %>'s</h3> -->
        <h3>PAST EVENTS</h3>

          <% @bookings.each do |booking| %>
            <% if booking.dj_profile_id == @dj_profile.id %>
              <p class="indiv-event">
                "<%= booking.name %>"
                in <%= booking.location %>
                on <%= Date::MONTHNAMES[booking.date.month] %> <%= booking.date.year%>
              </p>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>

    <!-- Form for booking -->
    <div class="form-section" id="collapseExample">
      <div class="d-none", id="dj-booking-form">
      <i class="far fa-times-circle" id="remove-btn"> <a href="#bio"></a></i>
      <%= render 'bookings/form' %>
      </div>
    </div>

    <!-- Reviews -->
    <div class="dj-card mt-4">
      <% if @dj_profile.reviews.blank?  %>
      <% else %>
      <h3><%= @dj_profile.stage_name %>'s reviews</h3>

        <% @dj_profile.reviews.each do |review| %>
        <div class="indiv-review">
          <p style="font-weight:500"><%= review.booking.user.username %> -
          <% review.fyre_stars.times do %>
            <i class="fas fa-fire" style="color:#BC5100; font-size:16px"></i>
            <% end %>
            <% (5-review.fyre_stars).times do %>
            <i class="fas fa-fire" style="color:#E5E5E5; font-size:16px"></i>
            <% end %>
          </p>
          <p class="comment">"<%= review.comment %>"</p>
        </div>
          <p style="font-size:10px;">Comment left on <span><%= Date::MONTHNAMES[review.booking.date.month] %></span> <span class="date"> <%= review.booking.date.year%></span></p>
        <% end %>
      <% end %>
    </div>

<script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<script>
  var scroll = new SmoothScroll('a[href*="#"]');
</script>

app/views/pages/home.html.erb
<div class="cadre-dj">

<!--   <div class="all-dj-btn">
    <%#= link_to 'All our DJs', dj_profiles_path, class: "btn btn-secondary" %>
  </div> -->

<div id="container-landing">
  <div class="dropdown">
    <h1 style="color:#E5E5E5">Start your FYRE !</h1>
    <h5>The best DJs for your events</h5>
    <button class="btn-ghost-orange dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Chose your genre
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%  DjProfile.genres.each do |genre| %>
      <%= link_to genre, root_path(query: genre), class:"dropdown-item" %>
      <% end %>
    </div>
    <% if @query %>
    <div class="d-flex justify-content-center" style="margin-top: 30px">
      <div class="genre-name" id="front-page">
        <%= @query %>
      </div>
    </div>
    <% end %>
  </div>
</div>



    <% @dj_profiles.each_with_index do |profile, index| %>
      <div>
        <%= link_to dj_profile_path(profile) do %>
          <%= cl_image_tag profile.user.photo, :class => "style-card img-fit", :id => "dj-#{index + 1}" %>
        <% end %>
      </div>
    <% end %>

</div>

app/views/pages/home2.html.erb
<div class="cadre-dj">

  <div class="all-dj-btn">
    <%= link_to 'All our DJs', dj_profiles_path, class: "btn btn-secondary" %>
  </div>


  <div class="dropdown">
  <h1 style="color:#E5E5E5">Hello FYRE !</h1>
  <h2>Bring FYRE to your venues</h2>
    <h5>What kind of music do you like ?</h5>
    <button class="btn-ghost-orange dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Chose your genre
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%  DjProfile.genres.each do |genre| %>
      <%= link_to genre, genre_path(genre), class:"dropdown-item"  %>
      <% end %>
    </div>
  </div>

  <% @djs = DjProfile.all.sample(21) %>
  <div>
    <%= image_tag "images_landing_page/nina_krav.jpg", :class => "style-card", :id => "dj-nina-k" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/laurent-garnier.jpg", :class => "style-card", :id => "dj-laurent-g" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/daft-punk.jpg", :class => "style-card", :id => "dj-daft-p" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/hunee.jpg", :class => "style-card", :id => "dj-hunee" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/l-imperatrice.jpg", :class => "style-card", :id => "dj-imperatrice" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/parcels.jpg", :class => "style-card", :id => "dj-parcels" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/justice.jpg", :class => "style-card", :id => "dj-justice" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/auntie-flo.jpg", :class => "style-card", :id => "dj-auntie-f" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/daniel-avery.jpg", :class => "style-card", :id => "dj-daniel-a" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/breakbot.jpg", :class => "style-card", :id => "dj-breakbot" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/solomun.png", :class => "style-card", :id => "dj-solomun" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/marc-rebillet.jpg", :class => "style-card", :id => "dj-marc-r" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/flavien-berger.jpg", :class => "style-card", :id => "dj-flavien-b" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/fkj.jpg", :class => "style-card", :id => "dj-fkj" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/todd-terje.jpg", :class => "style-card", :id => "dj-todd-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/jean-tonique.jpg", :class => "style-card", :id => "dj-jean-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/palms-trax.jpg", :class => "style-card", :id => "dj-palms-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/papooz.jpg", :class => "style-card", :id => "dj-papooz" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/lewis-ofman.jpg", :class => "style-card", :id => "dj-lewis-o" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/peggy-gou.jpg", :class => "style-card", :id => "dj-peggy-g" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/venice-club.jpg", :class => "style-card", :id => "dj-venice-c" %>
  </div>

  <div>
    <%#= image_tag "images_landing_page/fourtet.png", :class => "style-card", :id => "dj-fourtet" %>
  </div>






  <div>
    <%#= image_tag "images_landing_page/moby.jpg", :class => "style-card", :id => "dj-moby" %>
  </div>
</div>

app/views/pages/home3.html.erb
<div class="cadre-dj">

  <div class="all-dj-btn">
    <%= link_to 'All our DJs', dj_profiles_path, class: "btn btn-secondary" %>
  </div>


  <div class="dropdown">
  <h1 style="color:#E5E5E5">Hello FYRE !</h1>
  <h2>Bring FYRE to your venues</h2>
    <h5>What kind of music do you like ?</h5>
    <button class="btn-ghost-orange dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Chose your genre
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%  DjProfile.genres.each do |genre| %>
      <%= link_to genre, genre_path(genre), class:"dropdown-item"  %>
      <% end %>
    </div>
  </div>

  <div>
    <%= image_tag "images_landing_page/nina_krav.jpg", :class => "style-card", :id => "dj-nina-k" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/laurent-garnier.jpg", :class => "style-card", :id => "dj-laurent-g" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/daft-punk.jpg", :class => "style-card", :id => "dj-daft-p" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/hunee.jpg", :class => "style-card", :id => "dj-hunee" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/l-imperatrice.jpg", :class => "style-card", :id => "dj-imperatrice" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/parcels.jpg", :class => "style-card", :id => "dj-parcels" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/justice.jpg", :class => "style-card", :id => "dj-justice" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/auntie-flo.jpg", :class => "style-card", :id => "dj-auntie-f" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/daniel-avery.jpg", :class => "style-card", :id => "dj-daniel-a" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/breakbot.jpg", :class => "style-card", :id => "dj-breakbot" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/solomun.png", :class => "style-card", :id => "dj-solomun" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/marc-rebillet.jpg", :class => "style-card", :id => "dj-marc-r" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/flavien-berger.jpg", :class => "style-card", :id => "dj-flavien-b" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/fkj.jpg", :class => "style-card", :id => "dj-fkj" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/todd-terje.jpg", :class => "style-card", :id => "dj-todd-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/jean-tonique.jpg", :class => "style-card", :id => "dj-jean-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/palms-trax.jpg", :class => "style-card", :id => "dj-palms-t" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/papooz.jpg", :class => "style-card", :id => "dj-papooz" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/lewis-ofman.jpg", :class => "style-card", :id => "dj-lewis-o" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/peggy-gou.jpg", :class => "style-card", :id => "dj-peggy-g" %>
  </div>

  <div>
    <%= image_tag "images_landing_page/venice-club.jpg", :class => "style-card", :id => "dj-venice-c" %>
  </div>

  <div>
    <%#= image_tag "images_landing_page/fourtet.png", :class => "style-card", :id => "dj-fourtet" %>
  </div>






  <div>
    <%#= image_tag "images_landing_page/moby.jpg", :class => "style-card", :id => "dj-moby" %>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">

<div class="dashboard-card" id="top">
  <div class="d-flex justify-content-between align-items-center">
    <%= cl_image_tag @user.photo, height: 150, width: 200, crop: :fill %>
    <div>
      <% if @user.username.nil? %>
      <h1>Hello <%= @user.email %> ! </h1>
      <% else %>
      <h1>Hello <%= @user.username %> ! </h1>
      <% end %>
    </div>
    <div >
      <% if DjProfile.find_by(user_id: @user.id) %>
        <%= link_to "My DJ page",  dj_profile_path(DjProfile.find_by(user_id: @user.id).id), class: "btn-ghost-orange"  %>
        <% else %>
        <%= link_to "Create a DJ page",  new_dj_profile_path, class: "btn-ghost-orange"   %>
        <% end %>
    </div>
  </div>
</div>

<!-- DJ Dash-->
<% if DjProfile.find_by(user_id: @user.id) %>
<div class="dashboard-card">
  <h3 style="margin-bottom: 30px">My Bookings as DJ</h3>
  <% @bookings_dj.each do |booking| %>
    <div class="d-flex justify-content-between align-items-center" style="margin-bottom: 15px">
      <tr>

        <td><!-- Completed ?-->
          <% if booking.date < Date.today %>
            <h6 class="past">Event completed</h6>
          <% else %>
            <p> </p>
          <% end %>
        </td>

        <td><!-- Events details-->
          <h5 style="margin: 0; color: #E5E5E5"><%= booking.name %>, <%= booking.location %> | <%= Date::MONTHNAMES[booking.date.month] %>
          <%= booking.date.year%></h5>
        </td>

        <td><!-- Validated ?-->
          <% if booking.validated == false %>
            <%= simple_form_for(booking) do |f| %>
              <%= f.input :validated, as: :hidden, input_html: { value: true } %>
              <%= f.button :submit, "Accept Booking",class: "btn-ghost-orange" %>
            <% end %>
          <% else %>
            <h6 class="validated">Validated</h6>
          <% end %>
        </td>

      </tr>
      </div>

  <% end %>
</div>
<% end %>


<!-- User Dash-->

<div class="dashboard-card">
  <h3 style="margin-bottom: 30px">My Bookings as Promoter</h3>


  <tr>
    <% @bookings_user.each do |booking| %>
    <div class="d-flex align-items-center justify-content-between" style="margin-bottom: 15px">

        <!-- Past booking -->
        <div class="d-flex">
          <td><!-- Event passed? -->
            <% if booking.date < Date.today %>
              <h6 class="past mr-5">Event completed</h6>
            <% else %>
              <p> </p>
            <% end %>
          </td>

          <td><!-- Event details -->
            <h5 style="margin: 0; color: #E5E5E5"><%= booking.name %>, <%= booking.location %> | <%= Date::MONTHNAMES[booking.date.month] %>
              <%= booking.date.year%></h5>
          </td>
        </div>
      <div class="d-flex card-right">
        <td>
          <div class="booking-status">
            <!-- Booking status -->
            <% if booking.validated == false %>
              <h6 class="pending">Pending</h6>
            <% else %>
              <h6 class="validated">Validated</h6>
            <% end %>
          </div>
        </td>

        <td><!-- party has happened-->
          <% if booking.validated == true && booking.date < Date.today && booking.reviews.length == 0%>
            <%= link_to 'Rate this set', new_booking_review_path(booking), class:"btn-ghost-orange" %>

          <% elsif booking.reviews.length == 1%>
              <h6 class="past">Rated. Thanks!</h6>

          <% else %>
            <p> </p>
          <% end %>
        </td>

        <td><%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, booking_path(booking), method: :delete, data: {confirm: "Are you sure ?"} %>
        </td>
      </div>

      </div>

    <% end %>
    </tr>
  </div>

  <div class="dashboard-card">
    <h3 style="margin-bottom: 25px">Profile Admin</h3>

      <div class="d-flex justify-content-between dashboard" style="margin-bottom: 10px">
        <div>
          <%= link_to "Change my username", "#user-form", class:"btn-ghost", id:"username-btn"  %>
        </div>

        <div>
          <%= link_to "Change my password",  edit_user_registration_path, class:"btn-ghost"  %>
        </div>

        <div>
            <%= link_to "Change my picture", "#picture-form", class:"btn-ghost", id:"picture-btn"  %>
          </div>
        </div>
        <div class="d-flex justify-content-around" >

          <div class="d-none" , id="user-form">
            <%= render 'users/form' %>
          </div>

          <div class="d-none" , id="picture-form">
            <div id="admin-container">
              <div id="admin-form">
                <%= simple_form_for(@user) do |f| %>
                  <%= f.input :photo %>
                  <%= f.input :photo_cache, as: :hidden %>
                  <%= f.button :submit, "Update picture", class:"btn-ghost-orange" %>
                <% end %>
              </div>
            </div>
          </div>

      </div>

  </div>
</div>